# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-Client-TCPMulti
version:      0.0521
version_from: lib/POE/Component/Client/TCPMulti.pm
installdirs:  site
requires:
    POE:                           0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
